### ISSUE TITLE
make error of gzbridge

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gzweb#174]
**Original report ([archived issue](https://osrf-migration.github.io/gzweb-gh-pages/#!/osrf/gzweb/issues/174)) by Anonymous.**

----------------------------------------
when i try to run the command :  npm run deploy --- -m local , 
the error comes out 

make: *** [Debug/obj.target/gzbridge/GZNode.o] Error 4
make: Leaving directory '/home/nyf1209/gzweb/gzbridge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nyf1209/gzweb/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/home/nyf1209/.nvm/versions/node/v12.16.2/bin/node" "/home/nyf1209/gzweb/node_modules/.bin/node-gyp" "build" "-d"
gyp ERR! cwd /home/nyf1209/gzweb/gzbridge
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
There are node-gyp build errors, exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 deploy: `./deploy.sh "-c"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nyf1209/.npm/_logs/2020-04-15T02_55_03_138Z-debug.log

**Comment by LauraS25** [comment]
Hi! I have the same issue, did someone find a solution please?

**Comment by newcanopies** [comment]
Similar error:

`
npm run deploy --- -m local

> gzweb@1.3.0 deploy /home/user/gzweb
> ./deploy.sh "-m" "local"

sh: 1: ./deploy.sh: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! gzweb@1.3.0 deploy: `./deploy.sh "-m" "local"`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-22T12_05_30_203Z-debug.log
`

and npm start error below  
</details>
`npm start

> gzweb@1.3.0 start /home//user/gzweb
> if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port

internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/user/gzweb/gzbridge/build/Debug/gzbridge.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/gzbridge/server.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 start: `if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/esofi/.npm/_logs/2021-01-22T12_09_36_339Z-debug.log`

**Comment by newcanopies** [comment]
Similar error, is gzweb build possible against **node v12.20.0** ?

I already applied the ::boost patch

`
npm run deploy --- -m local

> gzweb@1.3.0 deploy /home/user/gzweb
> ./deploy.sh "-m" "local"

sh: 1: ./deploy.sh: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! gzweb@1.3.0 deploy: `./deploy.sh "-m" "local"`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-22T12_05_30_203Z-debug.log
`

and npm start error below  
</details>
`npm start

> gzweb@1.3.0 start /home//user/gzweb
> if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port

internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/user/gzweb/gzbridge/build/Debug/gzbridge.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/gzbridge/server.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 start: `if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-22T12_09_36_339Z-debug.log`

**Comment by FelipeGdM** [comment]
Hi @newcanopies!

> is gzweb build possible against node v12.20.0 ?

See #203, but in the moment the project supports node up to version 10.x

Nonetheless, I think your problem is on a previous step

> sh: 1: ./deploy.sh: Permission denied

You don't have the permission to run the script. Have you cloned the repo or downloaded the .zip version?

You may solve the problem with

```sh
sudo chmod +x ./scripts/deploy.sh
```

It will add execute permission `+x` to the script

**Comment by newcanopies** [comment]
> See #203, but in the moment the project supports node up to version 10.x

Thank you @FelipeGdM good to know about the underlying  "change in the V8 interface between Node 10 and 12"

> You don't have the permission to run the script. Have you cloned the repo or downloaded the .zip version?

git cloned/checked gzweb_1.4.0
I did catch this myself, and per your reminder, now listed it as an already performed step in building against Node 12 [issue 204]( https://github.com/osrf/gzweb/issues/204#issue-792213069). 

will keep my eyes peeled on your PR [for Node 12 build release](https://github.com/osrf/gzweb/pull/205
)

**Comment by newcanopies** [comment]
Thank you @FelipeGdM and @iche033 for 
Gazebo11 build against Node12 on Foxy/Ubuntu20.04

### **Note:** installing the below packages is REQUIRED by CMake:

**
`sudo apt install libgazebo11-dev`     
`sudo   apt-get install -y libjansson-dev`
`sudo apt   install imagemagick`
**
