### ISSUE TITLE
make error of gzweb

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gzweb#175]
**Original report ([archived issue](https://osrf-migration.github.io/gzweb-gh-pages/#!/osrf/gzweb/issues/175)) by Anonymous.**

----------------------------------------
i run the npm run deploy --- -m local following every step in the instructions
but the error occurred below

make: *** [Debug/obj.target/gzbridge/GZNode.o] Error 1
make: Leaving directory '/home/nyf1209/gzweb/gzbridge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nyf1209/gzweb/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/home/nyf1209/.nvm/versions/node/v12.16.2/bin/node" "/home/nyf1209/gzweb/node_modules/.bin/node-gyp" "build" "-d"
gyp ERR! cwd /home/nyf1209/gzweb/gzbridge
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
There are node-gyp build errors, exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 deploy: `./deploy.sh "-m" "local"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nyf1209/.npm/_logs/2020-04-15T03_21_21_824Z-debug.log

my npm version is 6.14.4 and my gazebo version is 10.2

**Comment by Maverick054** [comment]
Got the same issue.
Any fixes or alternatives ?

**Comment by iche033** [comment]
maybe try and see if it's fixed by pull request #194 ?

**Comment by Maverick054** [comment]
Thanks @iche033 !

**Comment by Maverick054** [comment]
Is there a method to display the output of gzweb on google cloud platform?

**Comment by chapulina** [comment]
> Is there a method to display the output of gzweb on google cloud platform?

@Maverick054 , that may be a better question for https://answers.gazebosim.org/.

---

I'm closing this since the `gzweb_1.4` branch is now compiling for Gazebo 9 and 11 (and most likely 10 too). Please ticket a new issue if there are other new compilation failures.
