### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by reinzor** [osrf/gzweb#182]
Hi,

Is `gzweb` still being maintained? Or what are your plans? I tried using together with `gazebo11` but it does not seem to compile on the `gzweb_1.4.0` branch. 

If we want to put effort into this, what should be the base branch? 

Thanks

PS: Great that gazebo is on github now, makes things much easier to contribute :)

**Comment by iche033** [comment]
hi, we still review pull requests as they come but we did not have a lot of time to fix issues recently.  

So contributions welcome. You can target `gzweb_1.4.0` if the changes are backward compatible, otherwise target `master`, thanks.
