### ISSUE TITLE
npm build/deploy error

### ISSUE THREAD

**Issue by anthonypan08** [osrf/gzweb#183]
I am following [this](http://gazebosim.org/tutorials?tut=gzweb_install&cat=gzweb) installation guide but ran into some issues at the npm step on build. Below is the error I am getting \
![Screenshot from 2020-06-17 21-24-24](https://user-images.githubusercontent.com/20074651/84967051-0cf90d00-b0e1-11ea-8b24-4ede55c70a7f.png).

I am running gazebo 9 with node version v8.17.0 and npm version 6.13.4. I tried both build on gzweb_1.4.0 and master

**Comment by reinzor** [comment]
Your `configure` step already seems to fail due to an already existing file. Please provide a proper log of the full clean `./deploy.sh` script.

**Comment by anthonypan08** [comment]
I think I figured it out, apparently I didn't install npm-gyp.
