### ISSUE TITLE
error: ‘v8::Handle’ has not been declared

### ISSUE THREAD

**Issue by Michdo93** [osrf/gzweb#203]
Hi I got following error on my Ubuntu 16.04 with Nodejs 12.14.1 and gzweb 1.4.0.

`npm run deploy --- -m local

> gzweb@1.4.0 deploy /home/kinetic/gzweb
> ./deploy.sh "-m" "local"

Build a local model database.
Only local models.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gzweb@1.4.0 No license field.

audited 748 packages in 12.098s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Running "concat:build_src" (concat) task

Running "concat:build_gz3d" (concat) task

Running "concat:build_gui" (concat) task

Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "uglify:build_src" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gz3d" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gui" (uglify) task
>> 1 file created 2.13 MB → 1.14 MB

Done.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gzweb version 2.0.0
CMake Warning (dev) at CMakeLists.txt:23 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  the old evaluation rules produce:

    'gzweb-2.0.0'

  but the new evaluation rules produce:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build type not selected: Release selected by default
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   signals
--   system
--   filesystem
--   program_options
--   regex
--   iostreams
--   date_time
--   chrono
--   atomic
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Boost version: 1.58.0
-- Looking for OGRE...
-- OGRE_PREFIX_WATCH changed.
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Checking for module 'jansson'
--   Found jansson, version 2.7
-- Checking for module 'gts'
--   Found gts, version 0.7.6
-- Boost version: 1.58.0
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   regex
--   thread
--   chrono
--   date_time
--   atomic
-- Looking for tinyxml.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kinetic/gzweb/build
Scanning dependencies of target gzcoarse
[ 50%] Building CXX object tools/CMakeFiles/gzcoarse.dir/gzcoarse.cc.o
[100%] Linking CXX executable gzcoarse
[100%] Built target gzcoarse
make: Entering directory '/home/kinetic/gzweb/gzbridge/build'
  CXX(target) Debug/obj.target/gzbridge/GZNode.o
In file included from ../GZNode.cc:19:0:
../GZNode.hh:36:34: error: ‘v8::Handle’ has not been declared
     public: static void Init(v8::Handle<v8::Object> exports);
                                  ^
../GZNode.hh:36:40: error: expected ‘,’ or ‘...’ before ‘<’ token
     public: static void Init(v8::Handle<v8::Object> exports);
                                        ^
../GZNode.cc:50:19: error: variable or field ‘Init’ declared void
 void GZNode::Init(Handle<Object> exports)
                   ^
../GZNode.cc:50:19: error: ‘Handle’ was not declared in this scope
../GZNode.cc:50:32: error: expected primary-expression before ‘>’ token
 void GZNode::Init(Handle<Object> exports)
                                ^
../GZNode.cc:50:34: error: ‘exports’ was not declared in this scope
 void GZNode::Init(Handle<Object> exports)
                                  ^
../GZNode.cc: In static member function ‘static void gzweb::GZNode::LoadMaterialScripts(const v8::FunctionCallbackInfo<v8::Value>&)’:
../GZNode.cc:106:65: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::NewFromUtf8(isolate, "Wrong number of arguments")));
                                                                 ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:113:77: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
        String::NewFromUtf8(isolate, "Wrong argument type. String expected.")));
                                                                            ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:119:44: error: no matching function for call to ‘v8::Value::ToString()’
   String::Utf8Value path(args[0]->ToString());
                                            ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63:0,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc: In static member function ‘static void gzweb::GZNode::SetConnected(const v8::FunctionCallbackInfo<v8::Value>&)’:
../GZNode.cc:129:38: error: no matching function for call to ‘v8::Value::BooleanValue()’
   bool value = args[0]->BooleanValue();
                                      ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63:0,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2603:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2603:8: note:   candidate expects 1 argument, 0 provided
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2606:51: note: candidate: v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2606:51: note:   candidate expects 1 argument, 0 provided
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc: In static member function ‘static void gzweb::GZNode::GetMaterialScriptsMessage(const v8::FunctionCallbackInfo<v8::Value>&)’:
../GZNode.cc:152:65: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::NewFromUtf8(isolate, "Wrong number of arguments")));
                                                                 ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:159:77: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
        String::NewFromUtf8(isolate, "Wrong argument type. String expected.")));
                                                                            ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:163:44: error: no matching function for call to ‘v8::Value::ToString()’
   String::Utf8Value path(args[0]->ToString());
                                            ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63:0,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:174:69: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   args.GetReturnValue().Set(String::NewFromUtf8(isolate ,msg.c_str()));
                                                                     ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc: In static member function ‘static void gzweb::GZNode::GetMessages(const v8::FunctionCallbackInfo<v8::Value>&)’:
../GZNode.cc:233:67: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     arguments->Set(i ,String::NewFromUtf8(isolate, msgs[i].c_str()));
                                                                   ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:233:68: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     arguments->Set(i ,String::NewFromUtf8(isolate, msgs[i].c_str()));
                                                                    ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:3412:22: note: declared here
                 bool Set(uint32_t index, Local<Value> value));
                      ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc: In static member function ‘static void gzweb::GZNode::Request(const v8::FunctionCallbackInfo<v8::Value>&)’:
../GZNode.cc:248:65: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         String::NewFromUtf8(isolate, "Wrong number of arguments")));
                                                                 ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:255:77: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
        String::NewFromUtf8(isolate, "Wrong argument type. String expected.")));
                                                                            ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2936:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc:261:47: error: no matching function for call to ‘v8::Value::ToString()’
   String::Utf8Value request(args[0]->ToString());
                                               ^
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63:0,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../GZNode.cc:18:
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../GZNode.cc: At global scope:
../GZNode.cc:289:14: error: variable or field ‘InitAll’ declared void
 void InitAll(Handle<Object> exports)
              ^
../GZNode.cc:289:14: error: ‘Handle’ was not declared in this scope
../GZNode.cc:289:27: error: expected primary-expression before ‘>’ token
 void InitAll(Handle<Object> exports)
                           ^
../GZNode.cc:289:29: error: ‘exports’ was not declared in this scope
 void InitAll(Handle<Object> exports)
                             ^
In file included from ../GZNode.cc:18:0:
../GZNode.cc:295:23: error: ‘InitAll’ was not declared in this scope
 NODE_MODULE(gzbridge, InitAll)
                       ^
/home/kinetic/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^
../GZNode.cc:295:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(gzbridge, InitAll)
 ^
gzbridge.target.mk:119: recipe for target 'Debug/obj.target/gzbridge/GZNode.o' failed
make: *** [Debug/obj.target/gzbridge/GZNode.o] Error 1
make: Leaving directory '/home/kinetic/gzweb/gzbridge/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/kinetic/gzweb/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-132-generic
gyp ERR! command "/usr/local/bin/node" "/home/kinetic/gzweb/node_modules/.bin/node-gyp" "rebuild" "-d"
gyp ERR! cwd /home/kinetic/gzweb/gzbridge
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
There are node-gyp build errors, exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.4.0 deploy: `./deploy.sh "-m" "local"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.4.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kinetic/.npm/_logs/2021-01-21T18_33_08_456Z-debug.log`

**Comment by FelipeGdM** [comment]
Hi @Michdo93!

This problem is due to a compatibility break between node v10 and v12, more specifically a change in the V8 interface in version 7.0 ([ref](https://github.com/nodejs/node/issues/23122))

In the moment, the project only supports node up to version 10.x
